### ISSUE TITLE
Some CSS improvements

### ISSUE THREAD

**Issue by skela** [markdowner/markdowner.github.io#5]
Had to make a few adjustments to get it to print right for some python coding snippets. Some adjustments to the lang-python css due to it adding an extra indent to the first line of python in each code block. Plus some adjustments to make it not strip out colours from the print out (it would strip away the code block backgrounds).

Do with this what you will ❤ 

```css

@media print {
  body{
    -webkit-print-color-adjust: exact; /*chrome & webkit browsers*/
    print-color-adjust: exact; /*firefox & IE */
  }
.pagebreak { page-break-before: always; } /* page-break-after works, as well */
}

.lang-python {
	padding: 0;
}



```
